- dev-util/monodevelop/monodevelop-5.0.1.ebuild
Git integration was causing a failed build with the 5.0.1 ebuild since
the git repository is understandably missing in the tarball. In
addition, on systems where gtk#-3 is also installed the build
experiences binding version mismatches (particularly with gdk-sharp and
glib-sharp).
This patch removes the git execution and sets specific_version for
libraries with judicial use of sed.
> build: Disable git integration, remedy binding

- dev-util/monodevelop/monodevelop-9999.ebuild
This patch moves the git submodule initialisation into our ebuild
src_unpack function, in addition to setting specific_version on all
csproj file library references we find to prevent gtk# version
mismatches.
In addition we select the 'stable' profile with a system prefix from the
new bespoke configuration script. We should probably reflect these as
exclusive use flags in a later version.
Finally, we add a use flag for tests which, surprisingly, don't appear
to require any further dependencies for successful compilation.
> build: Repair live ebuild

- dev-util/monodevelop/monodevelop-5.7.0.ebuild
There was a missing git-r3_fetch before git-r3_checkout.
> Fix monodevelop-5.7.0 ebuild.

- dev-util/monodevelop/monodevelop-5.9.0.431.ebuild
Use slot dependency so `gtk-sharp-2.99.1:3` isn't pulled in instead.
> monodevelop depends on gtk-sharp:2

- dev-util/monodevelop/files/5.9.5-kill-gnome.patch
- dev-util/monodevelop/files/5.9.5-skip_merged_tar.patch
- dev-util/monodevelop/monodevelop-5.9.5.5.ebuild
Well this seems to be somehow hackish :)
It makes this:
- clone monodevelop from github using versioned tag
- call configure and make dist to prepare dir which is normally delivered with all external libraries fetched too (they are not included in githubs packages)
- use prepared dir as before
I needed to alter some patches and create new one
It seems to work for me at least so I hope it can be usefull - maybe create monodevelop-9999 from it too (should work with little tweaking)?
> Added ebuild for monodevelop-5.9.5.5 (github)

- dev-lang/mono/files/mono-4.0.2.5-fix-decimal-ms-on-big-endian.patch
- dev-lang/mono/files/mono-4.0.2.5-fix-mono-dis-makefile-am-when-without-sgen.patch
- dev-lang/mono/mono-4.0.2.5.ebuild
- Patches to fix build for big-endian and without-sgen
- Bring configure switches in line with reality
- Other minor improvements
> dev-lang/mono-4.0.2.5.ebuild improvements

- dev-util/monodevelop/monodevelop-5.9.5.5.ebuild
I removed dev-dotnet/mono-addins from the latest monodevelop's (5.9.5.5) dependencies, which appears to have been unnecessary. mono-addins refuses to bulid without `gmcs` which doesn't look like it has been included in Mono 4, and monodevelop builds and runs fine without it. I'm not very familiar with .NET/Mono so I'm not certain that `gmcs` has been removed in 4.0, but if that's correct then mono-addins will probably need to be modified to have a dependency on Mono 3 specifically.
I didn't make this change in the other MonoDevelop's ebuilds because I hadn't tested them, but for anyone attempting to merge them on a system with this overlay's Mono 4 the same change will likely need to be made.
> Removed dev-dotnet/mono-addins from the latest monodevelop's dependencies

- eclass/gtk-sharp-module.eclass
As I told earlier - https://github.com/gentoo/dotnet/issues/91#issue-98855691 it is also good to check mono version. If it is old - then use gmcs, if it is new, then use mcs. But i don't know how to do this.
>  eclass/gtk-sharp-module.eclass

- dev-lang/mono/mono-9999.ebuild
Hi Heather and friends. With git 2.5.x it's been complaining to me about an unknown `-u` option to `git clone`. I'm pretty sure that's due to all the sloppy code in git-2.eclass and would probably be fine if that were cleaned up. However mono-9999 works fine with git-r3 (all submodules seem to update no problem).
Also it looks like this ebuild hasn't been touched in a while. I'm not sure what if anything from 4.2.0.179 is applicable here. I can't test a lot of the non-x86 and VB-only patches but I'll do some experiments and see what happens.
Here's the `./configure --help` after `src-prepare` as of yesterday if anybody's interested. https://gist.github.com/ormaaj/d8ed8e3acab0412af41c
> dev-lang/mono-9999: git-2 -> git-r3

- dev-lang/mono/mono-4.2.0.179.ebuild
- dev-lang/mono/mono-4.2.1.36.ebuild
> Remove references to ppc patch no longer required as of mono-4.2.0

- dev-lang/mono/mono-3.10.0.ebuild
- dev-lang/mono/mono-3.12.1.ebuild
- dev-lang/mono/mono-4.0.2.5.ebuild
- dev-lang/mono/mono-4.0.3.20.ebuild
- dev-lang/mono/mono-4.2.0.179.ebuild
- dev-lang/mono/mono-4.2.1.102-r1.ebuild
- dev-lang/mono/mono-4.2.2.10.ebuild
- dev-lang/mono/mono-9999.ebuild
paxmark.sh should be used instead which follows XT/PT marks correctly
Gentoo-Bug: https://bugs.gentoo.org/532244
I fixed this in the main tree but bumps overwrite the fixes so needs to be fixed in the overlay too.
> dev-lang/mono: do not call paxctl directly

- dev-dotnet/nuget/nuget-2.8.7-r1.ebuild
Gentoo-Bug: https://bugs.gentoo.org/show_bug.cgi?id=585548
Package-Manager: portage-2.2.28
mozroots is deprecated and "mozroots --import --sync --machine" don't work
(remove /usr/share/.mono/ to test)
use "cert-sync /etc/ssl/certs/ca-certificates.crt" instead
> dev-dotnet/nuget: solve NameResolutionFailure

- dev-dotnet/xdt-for-monodevelop/xdt-for-monodevelop-2.8.1.ebuild
- dev-dotnet/xdt-for-monodevelop/xdt-for-monodevelop-2.8.3.ebuild
For consistency with the rest of the tree i think the package should have testing keywords.
Also the stable keywords were set in initial commits so does not signify that the package has been tested.
> Change stable keywords to testing.

- dev-util/monodevelop/monodevelop-9999.ebuild
I fixed up monodevelop-9999 so that it at least builds.  Unfortunately, it crashes immediately with no interesting errors.  I can't tell yet if it's an upstream bug or something wrong with the way I build it.
> dev-util/monodevelop-9999 builds

- net-misc/sparkleshare/files/sparkleshare-1.4-mono-path.patch
- net-misc/sparkleshare/sparkleshare-1.4.ebuild
On my system, SparkleShare 1.4's configure script did not find the required System.dll supplied by Mono. This had two reasons:
* The file is included in dev-dotnet/referenceassemblies-pcl, which was not installed on my system and which the ebuild did not depend on
* The configure script tries to find the path to System.dll using pkg-config's "prefix" and "libdir" variables (for the "mono" package), which are not set in Gentoo.
The first point was easy to fix, the second a bit harder: The cleanest way would probably be to set the variable in mono.pc, but that files belongs to the mono ebuild and I did not want to touch it. Thus, I patched the configure script to also look in the Gentoo-specific path.
> Make SparkleShare find Mono's System.dll

- dev-dotnet/dotnet-cli/files/corefx-1.1.1-buildtools.patch
Gentoo is not the only portage-based distro. Others may lack /etc/os-release or have ID value != "gentoo".
E.g. Funtoo os-release file is either empty or has ID="funtoo" on systems installed with more recent stage builds.
Since this is solely ~amd64 ebuild, I think it's useless to assume there can be other runtimes required.
> Make BuildTools always select debian.8-x64 runtime

- dev-dotnet/dotnet-cli/dotnet-cli-1.1.1-r1.ebuild
- dev-dotnet/dotnet-cli/files/coreclr-1.0.6-clang39-commit-9db7fb1.patch
- dev-dotnet/dotnet-cli/files/coreclr-1.0.6-gcc6-clang39.patch
- dev-dotnet/dotnet-cli/files/coreclr-1.1.1-clang39-commit-9db7fb1.patch
- dev-dotnet/dotnet-cli/files/coreclr-1.1.1-exceptionhandling.patch
Well, all these patches are either were already present for older coreclr versions or found in upstream:
https://github.com/dotnet/coreclr/commit/7864b05cfcf16b1261962c5538e2f071759a1d9e
https://github.com/dotnet/coreclr/commit/9f4bf341ad236df7d16bbdba0c4111393ea141d2
https://github.com/dotnet/coreclr/commit/af5172c88b1a6753135ca4d4c01b4a4a479f8002
https://github.com/dotnet/coreclr/issues/7822#issuecomment-257947093
This allowed me to build dotnet-cli/dotnet-cli-1.1.1-r1 with GCC6 and Clang 3.9 successfully, yet I'm not sure whether these changes are backwards compatible with older GCC and Clang. Perhaps you can test it and this pull request can be of some use for you.
> Compatibility with gcc6 / clang3.9

- dev-dotnet/nuget/nuget-2.8.7-r3.ebuild
Added explicit signing to src_compile in ebuild to avoid error adding delay signed assembly to gac.  This is only for nuget.    I'll do one for xdt-for-monodevelop later, and there will be several others.  Lines 54 and 55 are added and the only changes from the -r2 ebuild.
> dev-dotnet/nuget fix for adding delay signed assembly to gac

- dev-dotnet/dbus-sharp/dbus-sharp-0.8.1.ebuild
This is similar to the issue in #305 where a lot of our ebuilds need to be changed to sign with sn (StrongName). Fixes dbus-sharp which is needed for Smuxi.
> dev-dotnet/dbus-sharp: StrongName fix (similar to #305)

- dev-dotnet/irony-daxnet/irony-daxnet-1.0.0_p2017083101.ebuild
fix for https://bugs.gentoo.org/635894
> dev-dotnet/irony-daxnet missing dependency added

- www-servers/xsp/xsp-9999.ebuild
xsp-9999.ebuild does not build at the moment because of banned autotools-utils in EAPI=6. Submitting quick fix.
> Make ebuild work (changed EAPI version)

- dev-dotnet/msbuild-tasks-api/msbuild-tasks-api-15.3-r1.ebuild
- dev-dotnet/newtonsoft-json/newtonsoft-json-6.0.8-r1.ebuild
Needed to install MSBuild, as the packages are required and their ebuilds
require the exbuild and exbuild_raw functions.
> Include xbuild functions in Newtonsoft and MSBuild tasks.

- dev-dotnet/nini/nini-1.1.0-r5.ebuild
if you enable pkg-config you get an error that einstall_pc_file is not defined, because of the missing import of mono-pkg-config
> added mono-pkg-config import

- net-irc/smuxi/smuxi-1.0.7.ebuild
- net-irc/smuxi/smuxi-9999.ebuild
tried to get the smuxi-1.0.7 to build still fails
but the smuxi-9999 builds now
needed to add a dependency for x11-ssh-askpass
is needed for password protected keys when you connect to a external engine via ssh+key
> Smuxi Fixes

- readme.md
eselect-repository supersedes app-admin/layman - ref https://wiki.gentoo.org/wiki/Eselect/Repository
> Update Readme to use eselect-repository

- Documentation/DotnetCore-Bin.md
Just spent a few minutes trying to figure out why `emerge` couldn't find these packages - thought I'd try to save some time for the next user that comes along.
> Update docs to reflect current portage category

- app-editors/visual-studio-code/visual-studio-code-1.39.2.ebuild
According to [this][1], vscode need `dev-libs/libdbusmenu` installed to pass the menu to Plasma.
[1]: https://wiki.archlinux.org/index.php/Visual_Studio_Code#Global_menu_not_working_in_KDE/Plasma
> [visual-studio-code]: add missing dependencies

- dev-dotnet/dotnetcore-sdk-bin-common/dotnetcore-sdk-bin-common-2.1.802.ebuild
- dev-dotnet/dotnetcore-sdk-bin-common/dotnetcore-sdk-bin-common-2.2.402.ebuild
- dev-dotnet/dotnetcore-sdk-bin-common/dotnetcore-sdk-bin-common-3.0.100.ebuild
- dev-dotnet/dotnetcore-sdk-bin-common/dotnetcore-sdk-bin-common-3.1.100_pre1.ebuild
I think this is the proper fix for the problem in #445 , please merge this as otherwise it's currently not working for the 3.0 slot.
> dev-dotnet/dotnetcore-sdk-bin-common: fix dependencies if there are revisions
