gentoo/dotnet

dev-util/monodevelop/files/5.7-downgrade_to_mvc3.patch
dev-util/monodevelop/monodevelop-5.7.0.ebuild

added patch to install Asp.Net addin from: https://bugs.gentoo.org/show_bug.cgi?id=458810#c13

patch to install ASP.Net addin

---

dev-lang/mono/files/systemweb.patch
dev-lang/mono/mono-9999-r1.ebuild

see https://github.com/mono/mono/pull/874 for details

patch for missing asp .net mvc properties

---

dev-lang/mono/files/systemweb2.patch
dev-lang/mono/mono-9999.ebuild

I propose to modify patch like this

some fixes was moved into upstream

---

dev-lang/mono/mono-4.0.2.5.ebuild
dev-lang/mono/mono-4.0.3.13.ebuild
dev-lang/mono/mono-4.0.3.19.ebuild

Sorry for the rapid-fire pull requests.

mono-4.0.[23]: Improve patch URL to include both commits in the patch

---

net-irc/smuxi/smuxi-1.0.ebuild

forgotten dependency

---

dev-lang/mono/files/fix-for-GitExtensions-issue-2710-another-resolution.patch
dev-lang/mono/mono-4.2.2.10-r1.ebuild

https://github.com/mono/mono/pull/2273#issuecomment-167094514

new version of patch

---

dev-util/monodevelop/files/local-nuget-icons.patch
dev-util/monodevelop/monodevelop-5.9.5.9-r1.ebuild

https://github.com/mrward/monodevelop-nuget-addin/issues/59

patch for local nupkg icons added

---

.gitattributes
dev-util/monodevelop/files/local-nuget-icons.patch

https://github.com/gentoo/dotnet/issues/170

.gitattributs added

---

dev-dotnet/xdt-for-monodevelop/xdt-for-monodevelop-2.8.1-r1.ebuild
dev-dotnet/xdt-for-monodevelop/xdt-for-monodevelop-2.8.1.ebuild
dev-dotnet/xdt-for-monodevelop/xdt-for-monodevelop-2.8.3.ebuild

https://github.com/gentoo/dotnet/issues/222#issuecomment-241236854

eapply_user was added

---

dev-dotnet/system-web-razor/files/disable-warning-as-error.patch
dev-dotnet/system-web-razor/system-web-razor-3.2.3_p2014092400.ebuild
dev-dotnet/system-web-webpages/files/remove-DataVisualiztion.patch
dev-dotnet/system-web-webpages/system-web-webpages-3.2.3_p2014092400.ebuild

somewhat like fix for
https://github.com/gentoo/dotnet/pull/234#issuecomment-244332308

helpers added

---

dev-dotnet/conemu-control-winforms/conemu-control-winforms-1.0.0_p2016051802-r1.ebuild
dev-dotnet/conemu-control-winforms/files/make-CommandLineBuilder-class-public.patch

I built GitExtensions locally, but unable to create ebuild for it yet

patch for CommandLineBuilder class visibility

---

dev-dotnet/system-web/files/autofac.patch
dev-dotnet/system-web/system-web-4.6.0.182-r1.ebuild

see http://blog.softelegance.com/net/setting-up-orchard-cms-on-mono/ for details
This patch adds missed functionality into System.Web for AutoFac IoC library

patch for AutoFac

---

dev-dotnet/notify-sharp/notify-sharp-3.0.3.ebuild

Fixes #276 
I only fixed it for version 3.0.3 of notify-sharp, since I did not test with the earlier one.

Depend on correct slots

---

dev-dotnet/libgdiplus/libgdiplus-4.2-r3.ebuild

https://bugs.gentoo.org/show_bug.cgi?id=604644

Bug 604644

---

.travis.yml

Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>

.travis.yml: update portage to 2.3.6, use valid profile for repoman

---

dev-dotnet/irony-daxnet/irony-daxnet-1.0.0_p2017083101.ebuild
dev-dotnet/msbuildtasks/msbuildtasks-1.5.0.240-r3.ebuild

more fixes for https://bugs.gentoo.org/635894

msbuildtasks - switching from xbuild o msbuild by default

---

dev-dotnet/sdb/sdb-9999.ebuild

Add SDB: Mono Soft Debugger Client from https://github.com/mono/sdb

Add sdb-9999.ebuild

---

app-editors/visual-studio-code/visual-studio-code-1.25.0-r1.ebuild

Package-Manager: Portage-2.3.40, Repoman-2.3.9

app-editors/visual-studio-code: Fix missing perms

---

eclass/dotnet.eclass

Fixes https://bugs.gentoo.org/659422

Inherit mono-env_pkg_setup in pkg_setup()

---

dev-dotnet/dotnetcore-aspnet-bin/dotnetcore-aspnet-bin-2.0.3.ebuild
dev-dotnet/dotnetcore-runtime-bin/dotnetcore-runtime-bin-2.0.4.ebuild
dev-dotnet/dotnetcore-runtime-bin/dotnetcore-runtime-bin-2.0.6.ebuild
dev-dotnet/dotnetcore-runtime-bin/dotnetcore-runtime-bin-2.0.7.ebuild
dev-dotnet/dotnetcore-sdk-bin/dotnetcore-sdk-bin-2.1.102.ebuild
dev-dotnet/dotnetcore-sdk-bin/dotnetcore-sdk-bin-2.1.105.ebuild
dev-dotnet/dotnetcore-sdk-bin/dotnetcore-sdk-bin-2.1.3.ebuild
dev-dotnet/dotnetcore-sdk-bin/dotnetcore-sdk-bin-2.1.302.ebuild
dev-dotnet/dotnetcore-sdk-bin/dotnetcore-sdk-bin-2.2.105.ebuild
dev-dotnet/dotnetcore-sdk/dotnetcore-sdk-1.0.0_pre2_p003121.ebuild
dev-dotnet/dotnetcore-sdk/dotnetcore-sdk-1.0.0_pre2_p003131.ebuild
dev-dotnet/dotnetcore-sdk/dotnetcore-sdk-1.1.1-r1.ebuild
dev-dotnet/dotnetcore-sdk/dotnetcore-sdk-1.1.1-r2.ebuild
dev-dotnet/dotnetcore-sdk/dotnetcore-sdk-1.1.1.ebuild

Revert "Allow things to be built with libressl support"
